<?php

namespace Tests;

use Carbon\Carbon;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Foundation\Testing\WithFaker;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication, RefreshDatabase, WithFaker;

    function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $knownDate = Carbon::create(2000, 01, 02, 03);
        Carbon::setTestNow($knownDate);
    }
}
